/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.css;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Xer
 */
public class Home extends javax.swing.JFrame  {
    private String meal;
    private int mealPrice;
    private String hall;
    private int hallPrice;
    private boolean weekendC;
    private boolean speedyPaymentC;
    private int record = 0;

    
    /**
     * Creates new form NewJFrame
     */
    public Home() {
        initComponents();
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mealTypes = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        hallTypes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        weekendChoice = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        speedyPayment = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        lessDeposit = new javax.swing.JTextField();
        adults = new javax.swing.JTextField();
        kids = new javax.swing.JTextField();
        checkout = new java.awt.Button();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        labelAdults = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        labelKids = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        label123891 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        labelCostPerMealAdults = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        labelCostPerMealKids = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel41 = new javax.swing.JLabel();
        labelTotalCostPerAdultMeal = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        labelTotalCostForKidMeals = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        labelTotalFoodCost = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel47 = new javax.swing.JLabel();
        labelGratuity = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        labelHomeFee = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        labelWeekendCharge = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        labelTaxes = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel55 = new javax.swing.JLabel();
        labelSubtotal = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        labelLessDeposit = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        labelLessSpeedyPayment = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel61 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel63 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caswell Cattering System");
        setBackground(new java.awt.Color(241, 241, 239));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel1.setBackground(new java.awt.Color(35, 109, 246));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(254, 209, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 65));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLayeredPane1.setBackground(new java.awt.Color(241, 241, 239));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caswell Cattering System");

        jLabel2.setText("Enter The Number Of Childern");

        jLabel3.setText("Enter The Number Of Adults");

        jLabel4.setText("Meal Type");

        mealTypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deluxe       $25.99", "Standard   $21.75" }));
        mealTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealTypesActionPerformed(evt);
            }
        });

        jLabel5.setText("Hall Type");

        hallTypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hall A\t     $1000", "Hall B\t     $850", "Hall C\t     $750", "Home\t     $0" }));
        hallTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallTypesActionPerformed(evt);
            }
        });

        jLabel6.setText("Weekend");

        weekendChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        weekendChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekendChoiceActionPerformed(evt);
            }
        });

        jLabel7.setText("Speedy Payment");

        speedyPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        speedyPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speedyPaymentActionPerformed(evt);
            }
        });

        jLabel8.setText("Less Deposit");

        lessDeposit.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lessDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessDepositActionPerformed(evt);
            }
        });

        adults.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        adults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultsActionPerformed(evt);
            }
        });

        kids.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        checkout.setBackground(new java.awt.Color(0, 0, 0));
        checkout.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        checkout.setForeground(new java.awt.Color(255, 255, 255));
        checkout.setLabel("Checkout");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(35, 109, 246));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Caswell Catering and Convention Services");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Final Bill");

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Number of Adults");

        labelAdults.setForeground(new java.awt.Color(255, 255, 255));
        labelAdults.setText("N/a");

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Number of Kids");

        labelKids.setForeground(new java.awt.Color(255, 255, 255));
        labelKids.setText("N/a");

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Gratuity");

        label123891.setForeground(new java.awt.Color(255, 255, 255));
        label123891.setText("20%");

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Cost Per Meal For Adults");

        labelCostPerMealAdults.setForeground(new java.awt.Color(255, 255, 255));
        labelCostPerMealAdults.setText("N/a");

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Cost Per Meal For Kids");

        labelCostPerMealKids.setForeground(new java.awt.Color(255, 255, 255));
        labelCostPerMealKids.setText("N/a");

        jSeparator2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null));

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Total Cost For Adult Meals");

        labelTotalCostPerAdultMeal.setForeground(new java.awt.Color(255, 255, 255));
        labelTotalCostPerAdultMeal.setText("N/a");

        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Total Cost For Kid Meals");

        labelTotalCostForKidMeals.setForeground(new java.awt.Color(255, 255, 255));
        labelTotalCostForKidMeals.setText("N/a");

        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Total Food Cost");

        labelTotalFoodCost.setForeground(new java.awt.Color(255, 255, 255));
        labelTotalFoodCost.setText("N/a");

        jSeparator3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null));

        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Gratuity");

        labelGratuity.setForeground(new java.awt.Color(255, 255, 255));
        labelGratuity.setText("N/a");

        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Home Fee");

        labelHomeFee.setForeground(new java.awt.Color(255, 255, 255));
        labelHomeFee.setText("N/a");

        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Weekend Charge");

        labelWeekendCharge.setForeground(new java.awt.Color(255, 255, 255));
        labelWeekendCharge.setText("N/a");

        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Taxes");

        labelTaxes.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxes.setText("N/a");

        jSeparator4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null));

        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Subtotal");

        labelSubtotal.setForeground(new java.awt.Color(255, 255, 255));
        labelSubtotal.setText("N/a");

        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Less Deposit");

        labelLessDeposit.setForeground(new java.awt.Color(255, 255, 255));
        labelLessDeposit.setText("N/a");

        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Less Speedy Payment");

        labelLessSpeedyPayment.setForeground(new java.awt.Color(255, 255, 255));
        labelLessSpeedyPayment.setText("N/a");

        jSeparator5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null));

        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Balance Due");

        labelTotal.setForeground(new java.awt.Color(255, 255, 255));
        labelTotal.setText("N/a");

        jSeparator6.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null));

        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Thank You For Choosing Caswell's ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel61)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTotal))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelLessSpeedyPayment))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelLessDeposit))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelSubtotal))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTaxes))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelWeekendCharge))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelHomeFee))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelGratuity))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTotalFoodCost))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTotalCostForKidMeals))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTotalCostPerAdultMeal))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel31))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel39))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAdults)
                            .addComponent(labelKids)
                            .addComponent(label123891)
                            .addComponent(labelCostPerMealAdults)
                            .addComponent(labelCostPerMealKids)))
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6))
                .addGap(65, 65, 65))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel29))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(labelAdults))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(labelKids))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(label123891))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(labelCostPerMealAdults))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(labelCostPerMealKids))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(labelTotalCostPerAdultMeal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(labelTotalCostForKidMeals))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(labelTotalFoodCost))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(labelGratuity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(labelHomeFee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(labelWeekendCharge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(labelTaxes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(labelSubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(labelLessDeposit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(labelLessSpeedyPayment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(labelTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel63)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mealTypes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(hallTypes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(weekendChoice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(speedyPayment, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lessDeposit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(adults, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(kids, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(checkout, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(hallTypes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(145, 145, 145))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lessDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(speedyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mealTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(weekendChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kids, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adults, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mealTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(hallTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(weekendChoice))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(speedyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lessDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mealTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealTypesActionPerformed
        // TODO add your handling code here:
        if(mealTypes.getSelectedIndex() == 0){
            meal = "deluxe";
            mealPrice = 25;
            
        }
        else{
            meal = "standard";
            mealPrice = 21;
        }
        
    }//GEN-LAST:event_mealTypesActionPerformed

    private void hallTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallTypesActionPerformed
        // TODO add your handling code here:
        switch (hallTypes.getSelectedIndex()) {
            case 0:
                hall = "Hall A";
                hallPrice = 1000;
                break;
            case 1:
                hall = "Hall B";
                hallPrice = 850;
                break;
            case 2:
                hall = "Hall C";
                hallPrice = 750;
                break;
            case 3:
                hall = "Home";
                hallPrice = 0;
                break;
            default:
                break;
        }
    }//GEN-LAST:event_hallTypesActionPerformed

    private void weekendChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekendChoiceActionPerformed
        // TODO add your handling code here:
        if(weekendChoice.getSelectedIndex() == 0){
            weekendC = true;
        }
        else{
            weekendC = false;
        }
    }//GEN-LAST:event_weekendChoiceActionPerformed

    private void lessDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessDepositActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_lessDepositActionPerformed

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        // TODO add your handling code here:
        
         
       int adult = Integer.parseInt(adults.getText());
       int kid = Integer.parseInt(kids.getText());
       int lessDepo = Integer.parseInt(lessDeposit.getText());
        
       int gratuity = 0;
       int meal_cost_adult = 0;
       int meal_cost_kid = 0;
       int speedy_payment_amount = 0;
       int subtotal = 0;
       int surcharge = 0;
       int taxes = 0;
       int total = 0;
       int total_adult_meals = 0;
       int total_kid_meals = 0;
       int total_food_cost = 0;
       int weekend_charge =0;
       
//       calculating
        total_adult_meals = adult * mealPrice;
        total_kid_meals = kid * ((mealPrice * 50) / 100);
        meal_cost_adult = mealPrice;
        meal_cost_kid = ((mealPrice*50) /100);
        total_food_cost = total_adult_meals + total_kid_meals;
        
//        taxes
        gratuity = (total_food_cost * 20) / 100;
        taxes = 6 * (total_food_cost) / 100;
        surcharge = (10 * total_food_cost) / 100;
        
        if (weekendC == true){
            subtotal = gratuity + total_food_cost + surcharge + hallPrice + taxes;
            
        }
        else{
            subtotal = gratuity + total_food_cost + hallPrice + taxes;
            
        }
//       speedy payment conditions
if (subtotal < 1000){
    speedy_payment_amount = (subtotal * 2) / 100;
}
else if (subtotal < 2000){
    speedy_payment_amount = (subtotal * 4) / 100;
}
else if (subtotal < 5000){
    speedy_payment_amount = (subtotal * 5) / 100;
}
else if (subtotal > 5000){
    speedy_payment_amount = (subtotal * 7) / 100;
}

// total

if (speedyPaymentC == true){
   total = subtotal - lessDepo - speedy_payment_amount;
}
else if (speedyPaymentC == false){
    total = subtotal - lessDepo;
}
        labelAdults.setText(adults.getText());
        labelKids.setText(kids.getText());
        labelCostPerMealKids.setText("$" + meal_cost_kid );
        labelCostPerMealAdults.setText("$" + meal_cost_adult );
        labelTotalCostPerAdultMeal.setText("$" + total_adult_meals);
        labelTotalCostForKidMeals.setText("$" + total_kid_meals );
        labelTotalFoodCost.setText("$" + total_food_cost);
        labelGratuity.setText("$" + gratuity);
        labelHomeFee.setText("$0");
        labelWeekendCharge.setText("$" + weekend_charge);
        labelTaxes.setText("$" + taxes);
        labelSubtotal.setText("$" + subtotal);
        labelLessDeposit.setText("$" + lessDepo);
        labelLessSpeedyPayment.setText("$" + speedy_payment_amount);
        labelTotal.setText("$" + total);
        
        
        String [] arr = { labelAdults.getText() , labelKids.getText(),  labelCostPerMealKids.getText() ,  labelCostPerMealAdults.getText()
                            , labelTotalCostPerAdultMeal.getText() , labelTotalCostForKidMeals.getText(), labelTotalFoodCost.getText(),
                            labelGratuity.getText() , labelHomeFee.getText(), labelWeekendCharge.getText(), labelTaxes.getText(), 
                               labelSubtotal.getText(), labelLessDeposit.getText(),labelLessSpeedyPayment.getText(),labelTotal.getText()
        };
        
        String name = "record" + record;
        write(name, arr);
        
      
        
        
        
        
    }//GEN-LAST:event_checkoutActionPerformed

    private void adultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultsActionPerformed
        // TODO add your handling code here:

        
        
        
        
    }//GEN-LAST:event_adultsActionPerformed

    private void speedyPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speedyPaymentActionPerformed
        // TODO add your handling code here:
        if(speedyPayment.getSelectedIndex() == 0){
            speedyPaymentC = true;
        }
        else{
            speedyPaymentC = false;
        }
    }//GEN-LAST:event_speedyPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
                
               
            }
        });
    }
  

    public void write (String filename, String[] x){
        try{
            BufferedWriter outputWriter = null;
        outputWriter = new BufferedWriter(new FileWriter(filename));
            for (String x1 : x) {
                outputWriter.write(x1 + "");
                outputWriter.newLine();
            }
        outputWriter.flush();  
        outputWriter.close();  
        }
        catch (IOException e){
            JOptionPane.showMessageDialog(this , "An Error Occurred While Writing to the File!");

        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adults;
    private java.awt.Button checkout;
    private javax.swing.JComboBox<String> hallTypes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField kids;
    private javax.swing.JLabel label123891;
    private javax.swing.JLabel labelAdults;
    private javax.swing.JLabel labelCostPerMealAdults;
    private javax.swing.JLabel labelCostPerMealKids;
    private javax.swing.JLabel labelGratuity;
    private javax.swing.JLabel labelHomeFee;
    private javax.swing.JLabel labelKids;
    private javax.swing.JLabel labelLessDeposit;
    private javax.swing.JLabel labelLessSpeedyPayment;
    private javax.swing.JLabel labelSubtotal;
    private javax.swing.JLabel labelTaxes;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTotalCostForKidMeals;
    private javax.swing.JLabel labelTotalCostPerAdultMeal;
    private javax.swing.JLabel labelTotalFoodCost;
    private javax.swing.JLabel labelWeekendCharge;
    private javax.swing.JTextField lessDeposit;
    private javax.swing.JComboBox<String> mealTypes;
    private javax.swing.JComboBox<String> speedyPayment;
    private javax.swing.JComboBox<String> weekendChoice;
    // End of variables declaration//GEN-END:variables
}

